# Project
group=com.mrcrayfish

# Java
java_version=21

# Common
minecraft_version=1.21.1
neo_form_version=1.21.1-20240808.144430

# Forge
forge_version=52.0.9

# Fabric
fabric_version=0.115.1+1.21.1
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.1.117
neoforge_version_range=[21.1,)
neoforge_loader_version_range=[2,)

# Mod options
mod_version=1.10.4
mod_name=Goblin Traders
mod_author=MrCrayfish
mod_id=goblintraders
mod_desc=Adds goblins that have unique trades to improve your adventure!
mod_homepage=https://mrcrayfish.com/mods/goblintraders
mod_source=https://github.com/MrCrayfish/GoblinTraders
mod_issues=https://github.com/MrCrayfish/GoblinTraders/issues
mod_license=MIT

# Dependency options
framework_version=0.9.4
catalogue_version=1.10.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false