package com.mrcrayfish.goblintraders.datagen;

import com.mrcrayfish.goblintraders.trades.GoblinTradeTags;
import com.mrcrayfish.goblintraders.trades.GoblinTrades;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.TagsProvider;
import net.minecraft.world.item.trading.VillagerTrade;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;

public class GoblinTradeTagsProvider extends TagsProvider<@NotNull VillagerTrade>
{
    public GoblinTradeTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider)
    {
        super(output, Registries.VILLAGER_TRADE, lookupProvider);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider)
    {
        this.tag(GoblinTradeTags.GOBLIN_TRADER_COMMON)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_APPLES_FOR_EMERALD)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_RAW_IRON_FOR_IRON_INGOTS)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_RAW_GOLD_FOR_GOLD_INGOTS)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_RAW_COPPER_FOR_COPPER_INGOTS)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_ROTTEN_FLESH_FOR_COAL)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_GRAVEL_FOR_FLINT)
            .add(GoblinTrades.GOBLIN_TRADER_COMMON_COBBLESTONE_FOR_EMERALDS);
        
        this.tag(GoblinTradeTags.GOBLIN_TRADER_UNCOMMON)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_EMERALD_FOR_GUNPOWDER)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_TURTLE_EGG_FOR_EMERALDS)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_PUFFERFISH_BUCKET_FOR_EMERALDS)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_EMERALDS_FOR_SPONGE)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_DAMAGED_ANVIL_AND_IRON_INGOTS_FOR_ANVIL)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_CHIPPED_ANVIL_AND_IRON_INGOTS_FOR_ANVIL)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_CLAY_FOR_TERRACOTTA)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_LEATHER_AND_PAPER_FOR_BOOKS)
            .add(GoblinTrades.GOBLIN_TRADER_UNCOMMON_AMETHYST_SHARDS_FOR_EMERALD);
        
        this.tag(GoblinTradeTags.GOBLIN_TRADER_RARE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_EXPERIENCE_BOTTLE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_NAME_TAG)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_PACKED_ICE_FOR_BLUE_ICE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_11)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_13)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_CAT)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_BLOCKS)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_FAR)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_MALL)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_MELLOHI)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_STAL)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_STRAD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_WARD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_WAIT)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_OTHERSIDE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_RELIC)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_PRECIPICE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_CREATOR)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_CREATOR_MUSIC_BOX)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_RAISER_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_HOST_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_WARD_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_EYE_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_BOLT_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_FOR_FLOW_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_ANGLER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_ARCHER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_ARMS_UP_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_BLADE_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_BREWER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_BURN_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_DANGER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_EXPLORER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_FLOW_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_FRIEND_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_GUSTER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_HEART_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_HEARTBREAK_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_HOWL_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_MINER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_MOURNER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_PLENTY_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_PRIZE_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_SCRAPE_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_SHEAF_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_SHELTER_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_SKULL_POTTERY_SHERD)
            .add(GoblinTrades.GOBLIN_TRADER_RARE_EMERALDS_AND_BRICK_FOR_SNORT_POTTERY_SHERD);

        this.tag(GoblinTradeTags.GOBLIN_TRADER_EPIC)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_CHAINMAIL_HELMET)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_CHAINMAIL_CHESTPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_CHAINMAIL_LEGGINGS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_CHAINMAIL_BOOTS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_COPPER_HELMET)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_COPPER_CHESTPLATE)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_COPPER_LEGGINGS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_EMERALDS_AND_IRON_INGOT_FOR_GOBLIN_TUNED_COPPER_BOOTS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_NIGHT_VISION)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_INVISIBILITY)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_LEAPING)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRONG_LEAPING)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_FIRE_RESISTANCE)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_SWIFTNESS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRONG_SWIFTNESS)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_WATER_BREATHING)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_HEALING)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRONG_HEALING)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_REGENERATION)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_LONG_REGENERATION)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRONG_REGENERATION)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRENGTH)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_STRONG_STRENGTH)
            .add(GoblinTrades.GOBLIN_TRADER_EPIC_GLASS_BOTTLE_AND_EMERALDS_FOR_SLOW_FALLING);

        this.tag(GoblinTradeTags.GOBLIN_TRADER_LEGENDARY)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_EMERALDS_AND_APPLES_FOR_MOON_BOOTS)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_EMERALDS_FOR_MYSTERY_MAP)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_PICKAXE)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_AXE)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_SHOVEL)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_HOE)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_SWORD)
            .add(GoblinTrades.GOBLIN_TRADER_LEGENDARY_EMERALDS_FOR_GOBLIN_TUNED_ELYTRA);

        this.tag(GoblinTradeTags.VEIN_GOBLIN_TRADER_COMMON)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_COMMON_CARROTS_FOR_EMERALD)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_COMMON_GLOWSTONE_FOR_GLOWSTONE_DUST)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_COMMON_NETHERRACK_FOR_EMERALD)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_COMMON_EMERALD_FOR_NETHER_WART);

        this.tag(GoblinTradeTags.VEIN_GOBLIN_TRADER_UNCOMMON)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_UNCOMMON_NETHERITE_INGOT_FOR_TOTEM_OF_UNDYING)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_UNCOMMON_ACIENT_DEBRIS_FOR_NETHERITE_SCRAP)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_UNCOMMON_NETHER_WART_AND_NETHER_BRICK_FOR_RED_NETHER_BRICKS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_UNCOMMON_GOLDEN_CARROT_FOR_EMERALDS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_UNCOMMON_NETHER_QUARTZ_ORE_FOR_EXPERIENCE_BOTTLE);

        this.tag(GoblinTradeTags.VEIN_GOBLIN_TRADER_RARE)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_GOLDEN_CARROTS_FOR_WITHER_SKELETON_SKULL)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_DIAMONDS_FOR_NETHERITE_UPGRADE_SMITHING_TEMPLATE)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_EMERALDS_FOR_RIB_ARMOR_TRIM_SMITHING_TEMPLATE)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_PIGSTEP)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_LAVA_CHICKEN)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_5)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_RARE_EMERALDS_FOR_MUSIC_DISC_TEARS);

        this.tag(GoblinTradeTags.VEIN_GOBLIN_TRADER_EPIC)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_SLOWNESS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_STRONG_SLOWNESS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_HARMING)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_STRONG_HARMING)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_POISON)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_LONG_POISON)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_STRONG_POISON)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_WEAKNESS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_WIND_CHARGED)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_WEAVING)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_OOZING)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_EPIC_EMERALDS_AND_GLASS_BOTTLE_FOR_INFESTED);
        
        this.tag(GoblinTradeTags.VEIN_GOBLIN_TRADER_LEGENDARY)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_HELMET)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_CHESTPLATE)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_LEGGINGS)
            .add(GoblinTrades.VEIN_GOBLIN_TRADER_LEGENDARY_NETHER_STAR_AND_DRAGON_HEAD_FOR_GOBLIN_TUNED_BOOTS);
    }
}
